class AppConst {
  static List<Map<String, dynamic>> avatar = [
    {"ImageURL": "https://avatar.iran.liara.run/public/2/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/3/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/4/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/5/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/6/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/7/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/8/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/9/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/10/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/11/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/12/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/13/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/14/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/16/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/18/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/80/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/81/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/82/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/83/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/84/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/85/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/86/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/87/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/88/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/89/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/90/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/91/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/92/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/93/"},
    {"ImageURL": "https://avatar.iran.liara.run/public/96/"},
  ];
}
